### ISSUE TITLE
Attribute error when attempting to render MeasureIt_Arch image (or vector)

### ISSUE THREAD

**Issue by meikasahara** [kevancress/MeasureIt_ARCH#126]
Blender version: 2.91.0 Alpha, branch: master, commit date: 2020-09-13 23:10, hash: 0f61b27e93f1, type: Release
build date: 2020-09-13, 23:15:45
platform: Linux
On the default startup scene, when attempting to add Bounds dimensions to the default cube and render the measurements, the following error appears (regardless of having chosen bounds, aligned dimensions or annotations):

`MeasureIt_ARCH: Rendering image
Rendering Object: 1 of: 3 Name: Light
Time: 2.765655517578125e-05
Rendering Object: 2 of: 3 Name: Camera
Time: 4.410743713378906e-05
Rendering Object: 3 of: 3 Name: Cube
Time: 0.002916574478149414
Python: Traceback (most recent call last):
  File "~/.config/blender/2.91/scripts/addons/MeasureIt_ARCH-master/measureit_arch_render.py", line 131, in execute
    render_result = render_main(self, context)
  File "~/.config/blender/2.91/scripts/addons/MeasureIt_ARCH-master/measureit_arch_render.py", line 289, in render_main
    draw_titleblock(context)
  File "~/.config/blender/2.91/scripts/addons/MeasureIt_ARCH-master/measureit_arch_main.py", line 553, in draw_titleblock
    rv3d = context.area.spaces[0].region_3d
AttributeError: 'SpaceProperties' object has no attribute 'region_3d'

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "~/.config/blender/2.91/scripts/addons/MeasureIt_ARCH-master/measureit_arch_render.py", line 131, in execute
    render_result = render_main(self, context)
  File "~/.config/blender/2.91/scripts/addons/MeasureIt_ARCH-master/measureit_arch_render.py", line 289, in render_main
    draw_titleblock(context)
  File "~/.config/blender/2.91/scripts/addons/MeasureIt_ARCH-master/measureit_arch_main.py", line 553, in draw_titleblock
    rv3d = context.area.spaces[0].region_3d
AttributeError: 'SpaceProperties' object has no attribute 'region_3d'

location: <unknown location>:-1`

**Comment by kevancress** [comment]
ahh, yep had some sloppy logic in the new setup for titleblock visibility I was testing out.

Should be fixed in ebed217b60ad1a4f6edf770bd4b7cbf1b5ea6292
